name: teraform destroy



on:

  workflow_dispatch:



env:

  aws-region: us-east-1

  my_bucket: sonam-bucket-tf

  tf_file: new.tfstate

  dyn_table: sonam-db



jobs:

  terraform:

    name: terraform

    runs-on: ubuntu-latest

   

    defaults:

      run:

        working-directory: ./grouping
    steps:

      - name: checkout

        uses: actions/checkout@v3



      - name: Terraform HasiCorp SetUp

        uses: hashicorp/setup-terraform@v2

        with:

          terraform_version: 1.1.7



      - name: AWS Credentials Configuration

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-region: ${{ env.aws-region }}

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

     

      

     

      - name: terraform init

        run:

          terraform init -reconfigure -backend-config="bucket=$my_bucket" -backend-config="key=$tf_file" -backend-config="dynamodb_table=$dyn_table"



  



      - name: terraform destroy

        run:

          terraform destroy -auto-approve

